name: Tutorials
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js (LTS)
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install patch-package globally
        run: npm install -g patch-package

      - name: Install zksync-cli globally
        run: npm install -g zksync-cli

      - name: Check zksync-cli version
        run: zksync-cli --version
